clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: 123456
  subscriptionsPerConnection: 2
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 2
  slaveConnectionMinimumIdleSize: 1
  slaveConnectionPoolSize: 2
  masterConnectionMinimumIdleSize: 1
  masterConnectionPoolSize: 4
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - redis://39.98.134.125:7001
    - redis://39.98.134.125:7002
    - redis://39.98.134.125:7003
    - redis://39.98.134.125:7004
    - redis://39.98.134.125:7005
    - redis://39.98.134.125:7006
    - redis://39.98.134.125:7007
    - redis://39.98.134.125:7008
    - redis://39.98.134.125:7009
  scanInterval: 1000
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
  checkSlotsCoverage: false
threads: 2
nettyThreads: 4
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"