spring:
  application:
    name: ecds-billpool
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.212.41
        ip: 39.98.134.125
        port: 8083
  datasource:
    username: root
    password: ubuntumysql
    url: jdbc:mysql://39.98.134.125:3306/bill_source?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 60000
    password: 123456
    cluster:
      max-redirects: 5
      nodes:
        - 39.98.134.125:7001
        - 39.98.134.125:7002
        - 39.98.134.125:7003
        - 39.98.134.125:7004
        - 39.98.134.125:7005
        - 39.98.134.125:7006
        - 39.98.134.125:7007
        - 39.98.134.125:7008
        - 39.98.134.125:7009
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1
  rabbitmq:
    host: 39.98.134.125
    port: 5672
    username: root
    password: ubunturabbitmq
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1739887652@qq.com
    password: fnvwcrwczbpqegfc
    nickname: bill_source_error
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

server:
  port: 8083

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bosssoft.ecds.entity

logging:
  config: classpath:log/log4j2.xml


